In [165]:
from sklearn import datasets
from sklearn.neighbors import KNeighborsClassifier
iris = datasets.load_iris()
#print(iris.DESCR)
features = iris.data
labels = iris.target
print(features[0],labels[0])


[5.1 3.5 1.4 0.2] 0


In [166]:
clf = KNeighborsClassifier()
clf.fit(features,labels)

pred = clf.predict([[31,1,1,1]])
print(pred)

[2]


In [167]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn import datasets
from sklearn import metrics

In [168]:
iris = datasets.load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [169]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [170]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [171]:
print(iris.data[0:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [172]:
print(iris.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [173]:
print(iris.data.shape)

(150, 4)


In [174]:
print(iris.target.shape)

(150,)


In [175]:
X_train,X_test,y_train,y_test = train_test_split(iris.data,iris.target,test_size=0.3)

In [176]:
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train,y_train)
y_pred = knn.predict(X_test)

In [177]:
y_pred

array([1, 1, 2, 1, 0, 0, 2, 2, 0, 1, 0, 2, 1, 2, 1, 2, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 2, 2, 0, 0, 1, 0, 2, 2, 1, 0, 1, 1, 2, 0, 1, 2, 0,
       1])

In [178]:
print("Accuracy of the model is :",metrics.accuracy_score(y_test,y_pred))

Accuracy of the model is : 0.9555555555555556


In [179]:
print(y_pred)

[1 1 2 1 0 0 2 2 0 1 0 2 1 2 1 2 1 1 0 1 0 0 0 0 0 1 1 2 2 0 0 1 0 2 2 1 0
 1 1 2 0 1 2 0 1]


In [181]:
if y_pred.max(1):
    print("Setosa")
elif y_pred.any(1):
    print("Versicolour") 
else:
    print("Virginica")

AxisError: axis 1 is out of bounds for array of dimension 1

In [ ]:
from keras_preprocessing.image import load_img
from keras_preprocessing.image import img_to_array
from keras_applications.vgg16 import preprocess_input,decode_predictions,VGG16

image = load_img(image_path,target_size=(224,224))
image = img_to_array(image)
image = image.reshape((1,image.shape[0],image.shape[1],image.shape[2]))
image = preprocess_input(image)
yhat = model.predict(image)
label = decode_predictions(yhat)
label = label[0][0]
classification = '%s (%.2f%%)' %(label[1] ,label[2] *100)

return render_template("index.html", prediction = classification)

In [1]:
from keras_preprocessing.image import load_img
from keras_preprocessing.image import img_to_array
from keras_applications.vgg16 import preprocess_input,decode_predictions,VGG16

from flask import Flask,render_template,request
app = Flask(__name__)

MODEL_PATH = 'MNIST/'
model = load_model(MODEL_PATH)
model._make_predict_function()     

@app.route('/',method=['GET'])
def hello_world():
    return render_template('index.html')

@app.route('/',method=['POST'])
def predict():
    imagefile = request.files['imagefile']
    image_path = "./MNIST/" + imagefile.filename
    imagefile.save(image_path)

	image = load_img(image_path, target_size=(224,224))
	image = img_to_array(image)
	image = image.reshape((1,image.shape[0],image.shape[1],image.shape[2]))
	image = preprocess_input(image)
	yhat = model.predict(image)
	label = decode_predictions(yhat)
	label = label[0][0]
	classification = '%s (%.2f%%)' %(label[1] ,label[2] *100)

	return render_template("index.html", prediction = classification)
    
if __name__ == '__main__':
    app.run(debug=True)

TabError: inconsistent use of tabs and spaces in indentation (<ipython-input-1-21bede5b0619>, line 22)

In [4]:
pip install autopep8


  Attempting uninstall: pycodestyle
    Found existing installation: pycodestyle 2.6.0
    Uninstalling pycodestyle-2.6.0:
      Successfully uninstalled pycodestyle-2.6.0



ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
flake8 3.9.0 requires pyflakes<2.4.0,>=2.3.0, but you have pyflakes 2.2.0 which is incompatible.
